language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t dnadawa/docker-example .

scripts:
  - docker run -e CI=true dnadawa/docker-example npm run test